// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcwwlY8nhWHjYw4agA0I445YsFzZ3KYtg',
    appId: '1:623115432063:web:198ddacd3592efa1298f4a',
    messagingSenderId: '623115432063',
    projectId: 'terrascope-6468',
    authDomain: 'terrascope-6468.firebaseapp.com',
    storageBucket: 'terrascope-6468.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI0xVXVnPmwxUxczh-QRZ1W-RN89t7QHc',
    appId: '1:623115432063:android:85d80283990faae8298f4a',
    messagingSenderId: '623115432063',
    projectId: 'terrascope-6468',
    storageBucket: 'terrascope-6468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCau27tieM3kZqPHx84Volflo39O_QzXRU',
    appId: '1:623115432063:ios:4cfb7ac356ecead7298f4a',
    messagingSenderId: '623115432063',
    projectId: 'terrascope-6468',
    storageBucket: 'terrascope-6468.firebasestorage.app',
    iosBundleId: 'com.example.terraScopeApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCau27tieM3kZqPHx84Volflo39O_QzXRU',
    appId: '1:623115432063:ios:4cfb7ac356ecead7298f4a',
    messagingSenderId: '623115432063',
    projectId: 'terrascope-6468',
    storageBucket: 'terrascope-6468.firebasestorage.app',
    iosBundleId: 'com.example.terraScopeApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcwwlY8nhWHjYw4agA0I445YsFzZ3KYtg',
    appId: '1:623115432063:web:11aa43aac4b6251a298f4a',
    messagingSenderId: '623115432063',
    projectId: 'terrascope-6468',
    authDomain: 'terrascope-6468.firebaseapp.com',
    storageBucket: 'terrascope-6468.firebasestorage.app',
  );
}
